---
title: "NES"
author: "David Kane"
date: "2/26/2020"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(rstanarm)
library(report)
library(tidyverse)

load("nes.rda")
```

```{r clean_data}
# This data is a mess. Where is the code book? Is this real NES data or some bs
# made up sample? This is a really good place to write down some thoughts on
# this data and where it comes from. Take a look at ROAS, pages 141 -- 142.

# We are trying to explain partyid7, which is the party identification of each
# respondent. Can we treat this as continuous? I think that lower numbers mean
# more Democratic.

# real_ideo is missing a lot. Should we just get rid of those rows? Depends on
# the time period we care about . . .

x <- nes %>% 
  as_tibble() %>% 
  select(year, partyid7, real_ideo, race_adj, 
         age_discrete, educ1, female, income) %>% 
  drop_na() %>% 
  mutate(gender = as.factor(ifelse(female == 1, "female", "non-female"))) %>% 
  mutate(race = as.factor(case_when(race_adj == 1 ~ "White",
                                    race_adj == 2 ~ "Black",
                                    TRUE ~ "Other")))
  
```

```{r model_1, cache=TRUE}
# What is the relationship, if any, between partyid7 and female? We will treat
# partyid7 as a continuous variable for this exercise, even though it is a
# categorical variable with 7 levels. Recall that 1 means Strong Democrat, 2
# means Democrat and so on, finishing with 7 for Strong Republican.

fit_1 <- stan_glm(data = x, partyid7 ~ gender, refresh = 0)
```

```{r model_2, cache=TRUE}
# What about the relationship between race and party ID? Need to have created a
# factor variable, or at least a character variable.

fit_2 <- stan_glm(data = x, partyid7 ~ race, refresh = 0)
```


```{r model_3, cache=TRUE}
fit_3 <- stan_glm(data = x, partyid7 ~ real_ideo, refresh = 0)
```

## Model Results

Here is a nicely printed summary of my model results, showing the relationship between party ID, on a 1 through 7 scale, and ideology, also on a 1 through 7 scale. Although these are ordered categories, I treat both variables as continuous.

```{r show_the_model, comment=NA}
print(fit_3, detail = FALSE, digits = 2)
```

It isn't the best thing I could imagine. I really want to figure out a way to add a caption. But it will do for now.



```{r left_over, include=FALSE}
x %>% 
  select(partyid7, gender, race, real_ideo) %>% 
  mutate(pred_gender = predict(fit_1, x)) %>% 
  mutate(pred_race = predict(fit_2, x)) %>% 
  mutate(pred_idea = predict(fit_3, x)) %>% 
  slice(8000:8010) # Good rows

```

